### ISSUE TITLE
error produced

### ISSUE THREAD

**Issue by moaeddy** [secgroundzero/tetanus#1]
**On Linux**

/bin/sh: 1: pwsh: not found
cat: inter_file: No such file or directory
rm: cannot remove 'inter_file': No such file or directory
Sub AutoOpen()

Traceback (most recent call last):
  File "tetanus.py", line 75, in <module>
    print loadVar + ' = ' + payload_list[i][0]
IndexError: list index out of range

**On Windows**

'pwsh' is not recognized as an internal or external command,
operable program or batch file.
'cat' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\tetanus.py", line 30, in <module>
    payload = subprocess.check_output("cat inter_file | iconv -t utf-16le | base64 | tr -d '\\n'", shell = True)
  File "C:\Python27\lib\subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'cat inter_file | iconv -t utf-16le | base64 | tr -d '\n'' returned non-zero exit status 255

**Comment by secgroundzero** [comment]
The error states that pwsh is not installed as explained in the readme file. This tool is not for Windows. if you want to use it on windows you need to change the code to call powershell not pwsh
